name: "CI: Security Gitleaks"
on:
  pull_request:
    branches: [main]
jobs:
  gitleaks:
    uses: Coalfire-CF/Actions/.github/workflows/ci-security-gitleaks.yml@88e02c851b87f8042147e1ba9f340b49ab1b628b # v1.0.0
