name: "CI: Security Trivy"
on:
  pull_request:
    branches: [main]
jobs:
  trivy:
    uses: Coalfire-CF/Actions/.github/workflows/ci-security-trivy.yml@7e2de0438dd4d4d4b302900dd2be9bb16ec276a2 # v1.3.0
