name: "CI: Terraform format"

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "**"
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
  pull_request:
    branches:
      - "**"
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"

jobs:
  terraform-docs:
    uses: Coalfire-CF/Actions/.github/workflows/ci-terraform-format.yml@7e2de0438dd4d4d4b302900dd2be9bb16ec276a2 # v1.3.0
    with:
      terraform_version: "1.15.7"
