name: Org Terraform Validate

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
      - "**/terraform/**"

jobs:
  terraform-validate:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-validate.yml@9e201c39c762245a1ccb2a487ed6a5c42c500fe7 # v0.16.1
    with:
      terraform_version: "1.15.7"
