name: Update README Tree on PR

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  readme-tree:
    uses: Coalfire-CF/Actions/.github/workflows/org-tree-readme.yml@df5fe1a0ee9068473c763609fc1d20c66df6ef94 # v0.14.0
    with:
      commit_message: "chore: update README tree"
      exclude_pattern: ".git|node_modules|.github|dist|build"
      working_directory: "."
