name: Org Terraform Validate

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
      - "**/terraform/**"

jobs:
  terraform-validate:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-validate.yml@23c6c8bc526102ed041f2e08a363e5ea2c2f0ec4 # v0.18.1
    with:
      terraform_version: "1.15.7"
