name: Org Terraform Validate

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
      - "**/terraform/**"

jobs:
  terraform-validate:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-validate.yml@162d71ff9bace6c2994b3b8d9e5bfc33f6b54eed # v0.18.0
    with:
      terraform_version: "1.15.7"
